package SoSe21.test.interpreter.plugin;

/*Generated by MPS */

import com.mbeddr.mpsutil.interpreter.rt.InterpreterEvaluationHelper;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class EvalHelper {
  private static InterpreterEvaluationHelper helper = new InterpreterEvaluationHelper("arithmetic");

  public static String eval(SNode n) {
    try {
      // Reset all values before interpreting 
      ParameterValuesSingleton.getIntegerValues().clear();
      ParameterValuesSingleton.getBooleanValues().clear();

      // Interpret the whole worksheet to save the values of variables 
      helper.evaluate(SNodeOperations.getNodeAncestor(n, CONCEPTS.Worksheet$QJ, false, false));

      Object result = helper.evaluate(n);
      if (result != null) {
        return String.valueOf(result);
      } else {
        return "Null result ";
      }
    } catch (Exception e) {
      return e.toString();
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Worksheet$QJ = MetaAdapterFactory.getConcept(0x2101cba8c59b492aL, 0xbe832a9e24bb3df8L, 0x1e75a3895f3bfb97L, "SoSe21.structure.Worksheet");
  }
}
