package SoSe21.test.interpreter.plugin;

/*Generated by MPS */

import com.mbeddr.mpsutil.interpreter.rt.InterpreterEvaluationHelper;
import org.jetbrains.mps.openapi.model.SNode;

public class EvalHelper {
  private static InterpreterEvaluationHelper helper = new InterpreterEvaluationHelper("arithmetic");

  public static String eval(SNode n) {
    try {
      Object result = helper.evaluate(n);
      if (result != null) {
        return String.valueOf(result);
      } else {
        return "Null result ";
      }
    } catch (Exception e) {
      return e.toString();
    }
  }
}
