package SoSe21.test.interpreter.plugin;

/*Generated by MPS */

import jetbrains.mps.smodel.structure.Extension;
import com.mbeddr.mpsutil.interpreter.rt.IInterpreter;
import com.mbeddr.mpsutil.interpreter.rt.CachedInterpreterFinder;

public class SoSe21Interpreter_extension extends Extension.Default<IInterpreter> {
  public SoSe21Interpreter_extension() {
    super("com.mbeddr.mpsutil.interpreter.InterpreterExtensionPoint");
  }

  public void activate() {
    CachedInterpreterFinder.getInstance().flushCache();
  }
  public void deactivate() {
    CachedInterpreterFinder.getInstance().flushCache();
  }

  public IInterpreter get() {
    return new InterpreterSoSe21Interpreter();
  }
}
