package TestSuite.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.SModifiersImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import com.mbeddr.mpsutil.interpreter.rt.InterpreterEvaluationHelper;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.baseLanguage.logging.runtime.model.LoggingRuntime;
import org.apache.log4j.Level;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public final class TestCase__BehaviorDescriptor extends BaseBHDescriptor {
  private static final Logger LOG = LogManager.getLogger(TestCase__BehaviorDescriptor.class);
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xf619d6b6154498cL, 0x845eb060aa497879L, 0x5a9016f2b09b64e6L, "TestSuite.structure.TestCase");

  public static final SMethod<String> getTestResult_idyKl3HQ$ImL = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("getTestResult").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("yKl3HQ$ImL").build(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getTestResult_idyKl3HQ$ImL);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static String getTestResult_idyKl3HQ$ImL(@NotNull SNode __thisNode__, SNode node) {
    InterpreterEvaluationHelper helper = new InterpreterEvaluationHelper("arithmetic");
    if ((SLinkOperations.getTarget(node, LINKS.function$Ys1v) == null)) {
      return "Fail";
    }
    if (SNodeOperations.getConcept(SLinkOperations.getTarget(node, LINKS.value$cnM3)).equals(CONCEPTS.Expression$O6)) {
      return "Fail";
    }
    Object functionResult = helper.evaluate(SLinkOperations.getTarget(node, LINKS.function$Ys1v));
    Object expected = helper.evaluate(SLinkOperations.getTarget(node, LINKS.value$cnM3));
    LoggingRuntime.logMsgView(Level.DEBUG, "Test function result: " + functionResult, TestCase__BehaviorDescriptor.class, null, null);
    LoggingRuntime.logMsgView(Level.DEBUG, "Test expected: " + expected, TestCase__BehaviorDescriptor.class, null, null);
    if (functionResult == expected) {
      return "Pass";
    }
    return "Fail";
  }

  /*package*/ TestCase__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) getTestResult_idyKl3HQ$ImL(node, (SNode) parameters[0]));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink function$Ys1v = MetaAdapterFactory.getContainmentLink(0xf619d6b6154498cL, 0x845eb060aa497879L, 0x5a9016f2b09b64e6L, 0x8b0543b7692cda1L, "function");
    /*package*/ static final SContainmentLink value$cnM3 = MetaAdapterFactory.getContainmentLink(0xf619d6b6154498cL, 0x845eb060aa497879L, 0x5a9016f2b09b64e6L, 0x5a9016f2b09ba45fL, "value");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Expression$O6 = MetaAdapterFactory.getConcept(0x2101cba8c59b492aL, 0xbe832a9e24bb3df8L, 0x1a76bf05f1a8eb2bL, "SoSe21.structure.Expression");
  }
}
